Models/Pages/RecipePage.cs
using EPiServer.Web;
using System.ComponentModel.DataAnnotations;
using static Head_Chef.Globals;

namespace Head_Chef.Models.Pages
{

    [ContentType(
        GUID = "8DFAB13C-4DA2-4309-983D-DE4AE4345B8C",
        GroupName = GroupNames.Specialized,
        DisplayName = "Recipe",
        Description = "This is a recipe template"
    )]
    [AvailableContentTypes(Availability.None)]
    public class RecipePage : SitePageData
    {
        [Display(
            Name = "Title",
            GroupName = SystemTabNames.Content,
            Order = 10
        )]
        public virtual string Title { get; set; } = string.Empty;

        [Display(
            Name = "Image",
            GroupName = SystemTabNames.Content,
            Order = 20
        )]
        public virtual string Image { get; set; } = string.Empty;

        [Display(
            Name = "Summary",
            GroupName = SystemTabNames.Content,
            Order = 30
        )]
        [UIHint(UIHint.Textarea)]
        public virtual string Summary { get; set; } = string.Empty;

        [Display(
            Name = "Instructions",
            GroupName = SystemTabNames.Content,
            Order = 40
        )]
        [UIHint(UIHint.Textarea)]
        public virtual string Instructions { get; set; } = string.Empty;

        [Display(
            Name = "Ingredients",
            GroupName = SystemTabNames.Content,
            Order = 50
        )]
        [UIHint(UIHint.Textarea)]
        public virtual string Ingredients { get; set; } = string.Empty;

        [Display(
            Name = "Time until ready",
            GroupName = SystemTabNames.Content,
            Order = 60
        )]
        public virtual int ReadyInMinutes { get; set; }

        [Display(
            Name = "Source url",
            GroupName = SystemTabNames.Content,
            Order = 70
        )]
        public virtual string SpoonacularSourceUrl { get; set; } = string.Empty;

        [Display(
            Name = "Id on Spoontacular",
            GroupName = SystemTabNames.Content,
            Order = 80
        )]
        [Editable(false)]
        public virtual int Id { get; set; }
    }
}

Models/ViewModels/RecipePageViewModel.cs
using Head_Chef.Models.Pages;
using Models.DDS;
using Newtonsoft.Json;
using static Head_Chef.Models.ViewModels.RecipeViewModel;

namespace Head_Chef.Models.ViewModels
{
    public class RecipePageViewModel : PageViewModel<RecipePage>
    {
        public RecipePageViewModel(RecipePage currentPage) : base(currentPage)
        {
        }
        [JsonProperty("vegetarian")]
        public bool Vegetarian { get; set; }

        [JsonProperty("vegan")]
        public bool Vegan { get; set; }

        [JsonProperty("glutenFree")]
        public bool GlutenFree { get; set; }

        [JsonProperty("dairyFree")]
        public bool DairyFree { get; set; }

        [JsonProperty("veryHealthy")]
        public bool VeryHealthy { get; set; }

        [JsonProperty("cheap")]
        public bool Cheap { get; set; }

        [JsonProperty("veryPopular")]
        public bool VeryPopular { get; set; }

        [JsonProperty("sustainable")]
        public bool Sustainable { get; set; }

        [JsonProperty("lowFodmap")]
        public bool LowFodmap { get; set; }

        [JsonProperty("weightWatcherSmartPoints")]
        public int WeightWatcherSmartPoints { get; set; }

        [JsonProperty("preparationMinutes")]
        public int PreparationMinutes { get; set; }

        [JsonProperty("cookingMinutes")]
        public int CookingMinutes { get; set; }

        [JsonProperty("aggregateLikes")]
        public int AggregateLikes { get; set; }

        [JsonProperty("healthScore")]
        public int HealthScore { get; set; }

        [JsonProperty("pricePerServing")]
        public double PricePerServing { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; } // //

        [JsonProperty("title")]
        public string Title { get; set; } // //

        [JsonProperty("readyInMinutes")]
        public int ReadyInMinutes { get; set; } // //

        [JsonProperty("servings")]
        public int Servings { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; } // //

        [JsonProperty("summary")]
        public string Summary { get; set; } // //        

        [JsonProperty("instructions")]
        public string Instructions { get; set; } // //

        [JsonProperty("spoonacularSourceUrl")]
        public string SpoonacularSourceUrl { get; set; }  // //

        /////////////


        [JsonProperty("extendedIngredients")]
        public List<ExtendedIngredient> ExtendedIngredients { get; set; }

        public IEnumerable<Comment> Comments { get; set; }

        public string Comment { get; set; } = string.Empty;
    }

    public class ExtendedIngredient
    {
        [JsonProperty("id")]
        public int Id { get; set; }        

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("nameClean")]
        public string NameClean { get; set; }

        [JsonProperty("original")]
        public string Original { get; set; }

        [JsonProperty("originalName")]
        public string OriginalName { get; set; }

        [JsonProperty("amount")]
        public double Amount { get; set; }

        [JsonProperty("unit")]
        public string Unit { get; set; }

        [JsonProperty("meta")]
        public List<string> Meta { get; set; }

        [JsonProperty("measures")]
        public Measures Measures { get; set; }
    }
}

Controllers/RecipePageController.cs
using EPiServer.Core.Internal;
using EPiServer.ServiceLocation;
using EPiServer.Web;
using EPiServer.Web.Mvc.Html;
using EPiServer.Web.Routing;
using Head_Chef.Business;
using Head_Chef.Business.Extensions;
using Head_Chef.Business.Services.Interfaces;
using Head_Chef.Models.Pages;
using Head_Chef.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;
using Models.DDS;

namespace Head_Chef.Controllers
{

    public class RecipePageController : PageControllerBase<RecipePage>
    {
        //private readonly IContentLoader _contentLoader;
        //private readonly ICommentService _commentService;
        //private readonly IContentRepository _contentRepository;
        //private readonly IServiceProvider _serviceProvider;
        //private readonly ILogger<RecipePageController> _logger;


        //public RecipePageController(IContentLoader contentLoader, ICommentService commentService, IContentRepository contentRepository, IServiceProvider serviceProvider, ILogger<RecipePageController> logger)
        //{
        //    _contentLoader = contentLoader;  
        //    _commentService = commentService;
        //    _contentRepository = contentRepository;  
        //    _serviceProvider = serviceProvider;
        //    _logger = logger;
        //}

        [HttpGet]        
        public IActionResult Index(RecipePage currentPage)
        {
            var model = new RecipePageViewModel(currentPage);
            
            //var comments =  _commentService.GetCommentsByPage(currentPage.Id);

            //if (comments != null)
            //{
            //    model.Comments = comments.ToList();
            //}
            ////////////////
            //try
            //{
            //    var comments = _commentService.GetCommentsByPage(currentPage.Id);
            //    model.Comments = comments;
            //}
            //catch (Exception ex) { _logger.LogError(ex.Message); }
            ////////////////
            //ViewData["UserComment"] = model.Comments;
            return View(model);
        }


        //// Get --- async
        //[HttpGet]
        //public async Task<IActionResult> IndexAsync(RecipePage currentPage)
        //{
        //    var model = new RecipePageViewModel(currentPage);

        //    var comments = await _commentService.GetCommentsByPageAsync(currentPage.Id);

        //    if (comments != null)
        //    {
        //        model.Comments = comments.ToList();
        //    }

        //    //ViewData["UserComment"] = model.Comments;
        //    return View(model);
        //}


        //[HttpPost]
        //public IActionResult PostComment(string commentText, int pageId)
        //{            
        //    var newComment = new Comment
        //    {
        //        PageId = pageId,
        //        Text = commentText 
        //    };

        //    _commentService.Save(newComment);

        //    //try
        //    //{
        //    //    _commentService.Save(newComment);
        //    //}
        //    //catch (Exception ex) { _logger.LogError(ex.Message); }


        //    var parent = GetParent();
        //    var c = _contentLoader.GetChildren<RecipePage>(parent).Where(x => x.Id == pageId).FirstOrDefault();

        //    var urlHelper = _serviceProvider.GetInstance<UrlResolver>();
        //    var friendlyUrl = urlHelper.GetUrl(c.ContentLink);

        //    return Redirect(friendlyUrl);

        //}

        //public ContentReference GetParent()
        //{
        //    var startPageContentLink = SiteDefinition.Current.StartPage;
        //    var startPage = _contentLoader.Get<StartPage>(startPageContentLink);
        //    var settingsPages = new List<SettingsPage>();
        //    startPage.GetDescendantsOfType(settingsPages);
        //    var settingsPage = settingsPages.FirstOrDefault();

        //    if (settingsPage != null)
        //    {
        //        var parent = settingsPage.RecipesContainer;

        //        if (parent != null)
        //        {
        //            return parent;
        //        }
        //    }

        //    return null;
        //}
    }
}

Views/RecipePage/Index.cshtml
@using EPiServer.Framework.Localization;
@using EPiServer.ServiceLocation;
@using EPiServer.Web.Mvc.Html;
@using Head_Chef.Business.Services.Interfaces;
@using Head_Chef.Models.Pages;
@using Head_Chef.Models.ViewModels;

@model RecipePageViewModel
@*@inject ICommentService _service
@{    
    _service.Save(new Models.DDS.Comment
        {                
            PageId = Model.Id,
            Text = "hej"            
        });
}*@
    

<div class=" container-sm pt-5">
    <h1 class="pt-3">@Model.CurrentPage.Title</h1>
    <div class="py-5">
        <div class="card shadow-sm">
            <div class="row g-0">
                <div class="col-lg-4">
                    <img src="@Model.CurrentPage.Image" class="h-100 w-100 overflow-hidden object-fit-cover hc-recipe-img shadow-md" alt="@Model.CurrentPage.Title">
                </div>
                <div class="col-lg-8">
                    <div class="card-body p-5">
                        <h2 class="card-title">@Model.CurrentPage.Title</h2>
                        <p class="card-text">@Html.Raw(Model.CurrentPage.Summary)</p>
                        <ul class="pb-3">
                            @Html.Raw(Model.CurrentPage.Ingredients)
                        </ul>
                        <p class="card-text">@Html.Raw(Model.CurrentPage.Instructions)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @* <div class="row">
        <form class="col-12 col-lg-6 d-flex gap-3 mb-auto py-5">
            <input type="hidden" name="pageId" value="@Model.CurrentPage.Id">
            <label for="commentText" class="hc-font-bigger align-self-center">Leave a Comment:</label>
            <textarea type="text" id="commentText" class="form-control w-50" name="commentText"></textarea>
            <input type="submit" value="Submit" class="btn btn-light">
        </form>
        <div class="col-12 col-lg-6 py-5">
            <p class="pb-2"> <i>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor condimentum lacinia quis vel eros. Magna sit amet purus gravida."</i></p>
            <p class="pb-2"><i>"Pharetra massa massa ultricies mi. Turpis tincidunt id aliquet risus feugiat in ante. In egestas erat imperdiet sed euismod nisi porta lorem." </i></p>
            <p class="pb-2"><i>"Dui ut ornare lectus sit. At tempor commodo ullamcorper a lacus. Proin fermentum leo vel orci porta non."</i></p>
        </div>
        </div>*@
                
                
        @*
    <div class="row">
        @using (Html.BeginForm("PostComment", "RecipePage", FormMethod.Post, new { @class="col-12 col-lg-6 d-flex gap-3 mb-auto py-5" } ))
        {
            <input type="hidden" name="pageId" value="@Model.CurrentPage.Id">
            <label for="commentText" class="hc-font-bigger align-self-center">Leave a Comment:</label>
            <textarea type="text" id="commentText" class="form-control w-50" name="commentText"></textarea>
            <input type="submit" value="Submit" class="btn btn-light">
        }
        <div class="col-12 col-lg-6 py-5">
        @foreach (var comment in Model.Comments) ---------------- (var comment in ViewData["UserComment"] as List<Comment>)
            {
            <p class="pb-2"> <i>"@(comment.Text)"</i></p>
            }
        </div>
    </div>
        *@    
</div>